### ISSUE TITLE
Relicense under dual MIT/Apache-2.0

### ISSUE THREAD

**Issue by dcvz** [oxideai/mlx-rs#55]
We plan to dual license `mlx-rs` - for this we need explicit approval from each contributor of copyrightable work.

To agree to relicensing, comment with :

`I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to choose either at their option.`

## Checklist

- [x] @dcvz 
- [x] @minghuaw

**Comment by dcvz** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to choose either at their option.

**Comment by minghuaw** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to choose either at their option.
